### ISSUE TITLE
Страница входа пользователя 

### ISSUE THREAD

**Issue by mr8bit** [oberdev/aircalc#16]
Скетч файла 
https://yadi.sk/d/TkyVYr0Ppq7OCw

**Comment by SkiesDrug** [comment]
![work page erly beta](https://user-images.githubusercontent.com/47172242/52156362-fb07fd00-2698-11e9-8680-6188aa6280a1.jpg)

**Comment by SkiesDrug** [comment]
![login page beta](https://user-images.githubusercontent.com/47172242/52156382-0fe49080-2699-11e9-84c6-4389527a7ad8.jpg)
