### ISSUE TITLE
Система авторизации пользователя

### ISSUE THREAD

**Issue by mr8bit** [oberdev/aircalc#7]
Добавить систему авторизации пользователя на главной страницы.

Так же ограничить доступ на остальных страницах для не авторизованных пользователей.

**Comment by mr8bit** [comment]
@oberdev 
Что за `stronghold.middleware.LoginRequiredMiddleware`, и чем не нравиться встроенная система авторизации пользователя ?

**Comment by fore10der** [comment]
@mr8bit 
авторизации пользователя ?
Мидлвар с гитхаба для принудительного требования логина для всех неавторизированных пользователей 
https://github.com/mgrouchy/django-stronghold

**Comment by mr8bit** [comment]
> > @oberdev
> > Что за `stronghold.middleware.LoginRequiredMiddleware`, и чем не нравиться встроенная система авторизации пользователя ?
> > Мидлвар с гитхаба для принудительного требования логина для всех неавторизированных пользователей
> > https://github.com/mgrouchy/django-stronghold

https://docs.djangoproject.com/en/2.1/topics/auth/default/ - решается добавлением одного декоратора `@login_required` над представлением

**Comment by fore10der** [comment]
> > > @oberdev
> > > Что за `stronghold.middleware.LoginRequiredMiddleware`, и чем не нравиться встроенная система авторизации пользователя ?
> > > Мидлвар с гитхаба для принудительного требования логина для всех неавторизированных пользователей
> > > https://github.com/mgrouchy/django-stronghold
> 
> https://docs.djangoproject.com/en/2.1/topics/auth/default/ - решается добавлением одного декоратора `@login_required` над представлением

В этом случае при увеличении кол-ва view придется каждому представлению добавлять этот декоратор
